### ISSUE TITLE
Develop Code that opens a specific show in Disney app or prime video

### ISSUE THREAD

**Issue by Alihassan325** [wdesimini/TVCommanderKit#14]
Hi @wdesimini 

Thanks for the library,  I want to add deep linking functionality in library. I want that I take a title like **"Reacher"** on prime video and opens it directly into the app in samsung tv.

However, it is possible to open app like **Prime Video** or **Disney** but how to open specific show using **Title** directly into the app.

Do you know how to do it ?

Thanks

**Comment by Kanagizhe** [comment]
@Alihassan325 
Hello, have you solved this problem? I don't know how to get the APP list on the TV and quickly launch the specified APP. Can you help me?

**Comment by Alihassan325** [comment]
Hi @Kanagizhe 

Yes I have solved it, I am able to open a specific app through using @wdesimini tvcommander code.

**Comment by Kanagizhe** [comment]
> Hi @Kanagizhe
> 
> Yes I have solved it, I am able to open a specific app through using @wdesimini tvcommander code with some modifications in the files.是的，我已经解决了这个问题，我可以通过使用 tvcommander 代码并在文件中进行一些修改来打开特定的应用程序。
Thanks for your reply, what code should I use when I want to start Youtube? can you show a snippet of your code
