### ISSUE TITLE
How we can open apps like (youtube, netflix) in Samsung TV

### ISSUE THREAD

**Issue by ahsan-mehmood-brainx** [wdesimini/TVCommanderKit#18]

**Comment by ahsan-mehmood-brainx** [comment]
@wdesimini can you guide me?

**Comment by Kanagizhe** [comment]
@ahsan-mehmood-brainx    @wdesimini 
Hello, have you solved this problem? I don't know now how to get the APP list on the TV and quickly launch the customized APP, can you help me?

**Comment by turgutoztunc** [comment]
did someone find a solution?

**Comment by ahsan-mehmood-brainx** [comment]
@wdesimini did you find the solution?

**Comment by wdesimini** [comment]
@Kanagizhe @turgutoztunc @ahsan-mehmood-brainx 
I added code to launch and fetch status of an installed app. I was unable to get the list of installed apps. I think you have to get them through Tizen Studio nowadays ([tizen website](https://tavicu.github.io/homebridge-samsung-tizen/extra/applications.html#list-with-ids))
