### ISSUE TITLE
How can I connect?

### ISSUE THREAD

**Issue by CT4TuEI3** [wdesimini/TVCommanderKit#34]
I don't quite understand how to connect to the TV. In the search, the TV finds and displays correctly. When I connect to it, writing the address, it gives the status Allowed, but when sending the command it gives an error. And I still don't quite understand what to write to the token. I expected that a four-digit code would be called on the TV as in similar applications. I entered both an arbitrary token and a uuid there - the status always fell allowed, but it gave an error when sending. Tell me, what could be the matter?

**Comment by wdesimini** [comment]
Let me clarify a few things that might help resolve your issue:
* Delegate passing back an allowed status means that you're authorized to send commands to the TV, so the connection itself should be valid.
* If you connected to the TV without a token and chose to allow the app when the TV prompted, that connection is considered authorized, and the token is stored in the `TVCommander` instance for future use.
* You only need to manually pass a token if you'd like to reconnect using a different `TVCommander` instance (by passing it into the initializer).
* Could you provide more details about the allowed status always being returned? I'm not encountering that when testing with my TV (Samsung Q7DAA 55 TV), so it would be helpful to understand what's going wrong here in your case.
* Lastly, `tvId` is purely for differentiating between TVs found during a search and is parsed from the SmartView SDK’s search results. You don't need to pass your own id value into the `TVCommander` (planning on refactoring this soon to clean it up a bit...).

Let me know if that helps, or if you can share more about the errors you're seeing when sending commands!

**Comment by CT4TuEI3** [comment]
I got some information. I found out that the four-digit code for creating a pair was called on Samsung TV models 2014-2015. Initially, I tried to connect to the UE65JU6000 and nothing worked for me. Later, I found out the reason that I described above. I tried the demo application in this repository from 2018 UE32N5300 and everything worked correctly for me. For 2014-2015 models, you need to look for a solution through the generation of a [token](https://github.com/aclytle/samsung_tv_ip_remote/issues/1#issuecomment-146362386) for auth_data.
