### ISSUE TITLE
Authorization through app instead of physical remote

### ISSUE THREAD

**Issue by Coger541** [wdesimini/TVCommanderKit#35]
Whenever I try to connect with Samsung TV through your demo app, I need to allow the prompt through physical remote. Is not its possible to allow the states through app instead of physical remote ?

**Comment by wdesimini** [comment]
Once you authorize your app with the physical remote, a token should be read through a message packet sent over the websocket connection. After that, you can pass that token into your next connection and authorize your app without use of the physical remote.

**Comment by Jack672** [comment]
Hi @wdesimini 

How can we implement this as I am noob in swift so I don't know too much about this

Thanks

> Once you authorize your app with the physical remote, a token should be read through a message packet sent over the websocket connection. After that, you can pass that token into your next connection and authorize your app without use of the physical remote.
